spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: api
    password: java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081
